type Query {
  # /lol/match/v5/matches/by-puuid/{puuid}/ids
  getMatchIDsByPUUID(puuid: String!): [String!]!

  # /lol/match/v5/matches/{matchId}
  getMatchByID(matchID: String!): MatchDto
  # /lol/match/v5/matches/{matchId}/timeline
}

type MatchDto {
  metadata: MetadataDto
  info: InfoDto
}

type MetadataDto {
  dataVersion: String #!
  matchId: String #!
  participants: [String!] #!
}

type InfoDto {
  gameCreation: Float! #	Unix timestamp for when the game is created on the game server (i.e., the loading screen).
  gameDuration: Float! #	Prior to patch 11.20, this field returns the game length in milliseconds calculated from gameEndTimestamp - gameStartTimestamp. Post patch 11.20, this field returns the max timePlayed of any participant in the game in seconds, which makes the behavior of this field consistent with that of match-v4. The best way to handling the change in this field is to treat the value as milliseconds if the gameEndTimestamp field isn't in the response and to treat the value as seconds if gameEndTimestamp is in the response.
  gameEndTimestamp: Float! #	Unix timestamp for when match ends on the game server. This timestamp can occasionally be significantly longer than when the match "ends". The most reliable way of determining the timestamp for the end of the match would be to add the max time played of any participant to the gameStartTimestamp. This field was added to match-v5 in patch 11.20 on Oct 5th, 2021.
  gameId: Float! #
  gameMode: String! #	Refer to the Game Constants documentation.
  gameName: String! #
  gameStartTimestamp: Float! #	Unix timestamp for when match starts on the game server.
  gameType: String! #
  gameVersion: String! #	The first two parts can be used to determine the patch a game was played on.
  mapId: Int! #	Refer to the Game Constants documentation.
  participants: [ParticipantDto!]! #
  platformId: String! #	Platform where the match was played.
  queueId: Int! #	Refer to the Game Constants documentation.
  teams: [TeamDto!]! #
  tournamentCode: String! #	Tournament code used to generate the match. This field was added to match-v5 in patch 11.13 on June 23rd, 2021.
}

type ParticipantDto {
  assists: Int! #
  baronKills: Int! #
  bountyLevel: Int! #
  champExperience: Int! #
  champLevel: Int! #
  championId: Int! #	Prior to patch 11.4, on Feb 18th, 2021, this field returned invalid championIds. We recommend determining the champion based on the championName field for matches played prior to patch 11.4.
  championName: String! #
  championTransform: Int! #	This field is currently only utilized for Kayn's transformations. (Legal values: 0 - None, 1 - Slayer, 2 - Assassin)
  consumablesPurchased: Int! #
  damageDealtToBuildings: Int! #
  damageDealtToObjectives: Int! #
  damageDealtToTurrets: Int! #
  damageSelfMitigated: Int! #
  deaths: Int! #
  detectorWardsPlaced: Int! #
  doubleKills: Int! #
  dragonKills: Int! #
  firstBloodAssist: Boolean! #
  firstBloodKill: Boolean! #
  firstTowerAssist: Boolean! #
  firstTowerKill: Boolean! #
  gameEndedInEarlySurrender: Boolean! #
  gameEndedInSurrender: Boolean! #
  goldEarned: Int! #
  goldSpent: Int! #
  individualPosition: String! #	Both individualPosition and teamPosition are computed by the game server and are different versions of the most likely position played by a player. The individualPosition is the best guess for which position the player actually played in isolation of anything else. The teamPosition is the best guess for which position the player actually played if we add the constraint that each team must have one top player, one jungle, one middle, etc. Generally the recommendation is to use the teamPosition field over the individualPosition field.
  inhibitorKills: Int! #
  inhibitorTakedowns: Int! #
  inhibitorsLost: Int! #
  item0: Int! #
  item1: Int! #
  item2: Int! #
  item3: Int! #
  item4: Int! #
  item5: Int! #
  item6: Int! #
  itemsPurchased: Int! #
  killingSprees: Int! #
  kills: Int! #
  lane: String! #
  largestCriticalStrike: Int! #
  largestKillingSpree: Int! #
  largestMultiKill: Int! #
  longestTimeSpentLiving: Int! #
  magicDamageDealt: Int! #
  magicDamageDealtToChampions: Int! #
  magicDamageTaken: Int! #
  neutralMinionsKilled: Int! #
  nexusKills: Int! #
  nexusTakedowns: Int! #
  nexusLost: Int! #
  objectivesStolen: Int! #
  objectivesStolenAssists: Int! #
  participantId: Int! #
  pentaKills: Int! #
  perks: PerksDto #
  physicalDamageDealt: Int! #
  physicalDamageDealtToChampions: Int! #
  physicalDamageTaken: Int! #
  profileIcon: Int! #
  puuid: String! #
  quadraKills: Int! #
  riotIdName: String! #
  riotIdTagline: String! #
  role: String! #
  sightWardsBoughtInGame: Int! #
  spell1Casts: Int! #
  spell2Casts: Int! #
  spell3Casts: Int! #
  spell4Casts: Int! #
  summoner1Casts: Int! #
  summoner1Id: Int! #
  summoner2Casts: Int! #
  summoner2Id: Int! #
  summonerId: String! #
  summonerLevel: Int! #
  summonerName: String! #
  teamEarlySurrendered: Boolean! #
  teamId: Int! #
  teamPosition: String! #	Both individualPosition and teamPosition are computed by the game server and are different versions of the most likely position played by a player. The individualPosition is the best guess for which position the player actually played in isolation of anything else. The teamPosition is the best guess for which position the player actually played if we add the constraint that each team must have one top player, one jungle, one middle, etc. Generally the recommendation is to use the teamPosition field over the individualPosition field.
  timeCCingOthers: Int! #
  timePlayed: Int! #
  totalDamageDealt: Int! #
  totalDamageDealtToChampions: Int! #
  totalDamageShieldedOnTeammates: Int! #
  totalDamageTaken: Int! #
  totalHeal: Int! #
  totalHealsOnTeammates: Int! #
  totalMinionsKilled: Int! #
  totalTimeCCDealt: Int! #
  totalTimeSpentDead: Int! #
  totalUnitsHealed: Int! #
  tripleKills: Int! #
  trueDamageDealt: Int! #
  trueDamageDealtToChampions: Int! #
  trueDamageTaken: Int! #
  turretKills: Int! #
  turretTakedowns: Int! #
  turretsLost: Int! #
  unrealKills: Int! #
  visionScore: Int! #
  visionWardsBoughtInGame: Int! #
  wardsKilled: Int! #
  wardsPlaced: Int! #
  win: Boolean! #
}

type PerksDto {
  statPerks: PerkStatsDto #
  styles: [PerkStyleDto!]! #
}
type PerkStatsDto {
  defense: Int! #
  flex: Int! #
  offense: Int! #
}

type PerkStyleDto {
  description: String! #
  selections: [PerkStyleSelectionDto!]! #
  style: Int! #
}
type PerkStyleSelectionDto {
  perk: Int! #
  var1: Int! #
  var2: Int! #
  var3: Int! #
}

type TeamDto {
  bans: [BanDto!]! #
  objectives: ObjectivesDto #
  teamId: Int! #
  win: Boolean! #
}

type BanDto {
  championId: Int! #
  pickTurn: Int! #
}

type ObjectivesDto {
  baron: ObjectiveDto #
  champion: ObjectiveDto #
  dragon: ObjectiveDto #
  inhibitor: ObjectiveDto #
  riftHerald: ObjectiveDto #
  tower: ObjectiveDto
}

type ObjectiveDto {
  first: Boolean! #
  kills: Int #!
}
